spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${CHAT_DB_HOST}:27017/${CHAT_DB_NAME}?authSource=admin
  cloud:
    compatibility-verifier:
      enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  mvc:
    async:
      request-timeout: -1

server:
  port: ${CHAT_SERVICE_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  # Health check에서 redis 자동으로 검사함. 추후 redis 추가하면 아래 3줄 없애도 무방
  health:
    redis:
      enabled: false
info:
  app:
    name: chat-service
    description: authentication service
    version: 0.0.1

service:
  auth:
    url: http://${AUTH_SERVICE_HOST}:${AUTH_SERVICE_PORT}
  chat:
    url: http://${CHAT_SERVICE_HOST}:${CHAT_SERVICE_PORT}

firebase:
  service-account-path: ${FIREBASE_SERVICE_ACCOUNT_PATH}

gms:
  api:
    url: https://gms.ssafy.io/gmsapi/api.openai.com/v1/chat/completions
    key: ${GMS_KEY}
    model: gpt-4.1-nano
    system-prompt: Answer in Korean
    max-tokens: 4096
    temperature: 0.3
  embedding:
    url: https://gms.ssafy.io/gmsapi/api.openai.com/v1/embeddings
    key: ${GMS_KEY}
    model: text-embedding-3-large

chroma:
  url: http://${CHROMA_HOST:localhost}:${CHROMA_PORT:8000}
  collection-name: lodgings
  query:
    n-results: 5