spring:
  application:
    name: travel-service
  datasource:
    url: jdbc:mysql://${TRAVEL_DB_HOST}:${TRAVEL_DB_PORT}/${TRAVEL_DB_NAME}
    username: ${DB_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


server:
  port: ${TRAVEL_SERVICE_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  # Health check에서 redis 자동으로 검사함. 추후 redis 추가하면 아래 3줄 없애도 무방
  health:
    redis:
      enabled: false
info:
  app:
    name: travel-service
    description: authentication service
    version: 0.0.1

file:
  upload-dir: C:/travel/images
