spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - 'http://localhost:3000'
                  - 'https://ssafywte.site'
                  - 'http://ssafywte.site'
                allowedMethods: '*'
                allowedHeaders: '*'
#                allowedCredentials: true
          routes:
            - id: auth-service-public
              uri: http://${AUTH_SERVICE_HOST}:${AUTH_SERVICE_PORT}
              predicates:
                - Path=/auth-service/api/v1/auth/signup, /auth-service/api/v1/auth/login, /auth-service/api/v1/auth/regist
              filters:
                - StripPrefix=1

            - id: auth-service-private
              uri: http://${AUTH_SERVICE_HOST}:${AUTH_SERVICE_PORT}
              predicates:
                - Path=/auth-service/api/**
              filters:
                - StripPrefix=1
                - AuthorizationHeaderFilter

            - id: payment-service
              uri: http://${PAYMENT_SERVICE_HOST}:${PAYMENT_SERVICE_PORT}
              predicates:
                - Path=/payment-service/api/**
              filters:
                - StripPrefix=1
                - name : AuthorizationHeaderFilter

            - id: chat-service
              uri: http://${CHAT_SERVICE_HOST}:${CHAT_SERVICE_PORT}
              predicates:
                - Path=/chat-service/api/**
              filters:
                - StripPrefix=1
                - AuthorizationHeaderFilter

            - id: travel-service
              uri: http://${TRAVEL_SERVICE_HOST}:${TRAVEL_SERVICE_PORT}
              predicates:
                - Path=/travel-service/api/**
              filters:
                - StripPrefix=1
                - AuthorizationHeaderFilter
jwt:
  secret: ${JWT_SECRET:default_secret_key_which_must_be_long_enough}
server:
  port: 8081