package io.ssafy.chat.common.enums;

public enum NotificationType {
    CHAT_MESSAGE,
    SYSTEM,
    SETTLEMENT_REMINDER,
    DUES_REMINDER,
    DUES_CREATED,
    ONSITE_PAYMENT_REQUEST,
    ONSITE_PAYMENT_COMPLETE,
    VOTE_CREATED,
    VOTE_REJECTED,
    PAYMENT_APPROVED,
    PAYMENT_REJECTED
}
