export const images = {
  logo: require('../assets/icons/ENCOLOGO_hamco.png'),
  phone: require('../assets/icons/phone_hamco.png'),
  welcome: require('../assets/icons/welcom_hamco.png'),
  homeIcon: require('../assets/icons/Home.png'),
  profileIcon:require('../assets/icons/Profile.png'),
  walletIcon: require('../assets/icons/Wallet.png'),
  qr: [
    require('../assets/images/qr0.png'),
    require('../assets/images/qr1.png'),
    require('../assets/images/qr2.png'),
    require('../assets/images/qr3.png'),
  ],
  barcode: [
    require('../assets/images/barcode0.png'),
    require('../assets/images/barcode1.png'),
    require('../assets/images/barcode2.png'),
    require('../assets/images/barcode3.png'),
  ],
  card1: require('../assets/images/card1.png'),
  card2: require('../assets/images/card2.png'),
  card3: require('../assets/images/card3.png'),
  card4: require('../assets/images/card4.png'),
  user: require('../assets/images/user.png'),
};
