spring:
  application:
    name: payment-service
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jackson: # ← 추가
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:mysql://${PAYMENT_DB_HOST}:${PAYMENT_DB_PORT}/${PAYMENT_DB_NAME}
    username: ${DB_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  cloud:
    compatibility-verifier:
      enabled: false
    openfeign:
      circuitbreaker:
        enabled: true
        group:
          enabled: true
server:
  port: ${PAYMENT_SERVICE_PORT}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB

service:
  auth:
    url: http://${AUTH_SERVICE_HOST}:${AUTH_SERVICE_PORT}

gms:
  url: ${GMS_URL}
  key: ${GMS_KEY}
  model: ${GMS_MODEL}

clova:
  ocr:
    invoke-url: ${CLOVA_OCR_INVOKE_URL:}
    secret: ${CLOVA_OCR_SECRET:}
    version: ${CLOVA_OCR_VERSION:V1}
    timeout-ms: ${CLOVA_OCR_TIMEOUT_MS:15000}

minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  bucket: ${MINIO_BUCKET}

app:
  file-base-url: ${FILE_BASE_URL}

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      authServiceClient:
        base-config: default
      auth-service:
        base-config: default

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers
  endpoint:
    health:
      show-details: always
info:
  app:
    name: payment-service
    description: authentication service
    version: 0.0.1