spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://${AUTH_DB_HOST}:${AUTH_DB_PORT}/${AUTH_DB_NAME}
    username: ${DB_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  cloud:
    compatibility-verifier:
      enabled: false
jwt:
  secret: ${JWT_SECRET}
  access-expiration: 3600000
  refresh-expiration: 1209600000
server:
  port: ${AUTH_SERVICE_PORT}
service:
  payment:
    url: http://${PAYMENT_SERVICE_HOST}:${PAYMENT_SERVICE_PORT}
  chat:
    url: http://${CHAT_SERVICE_HOST}:${CHAT_SERVICE_PORT}
