spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://${AUTH_SERVICE_HOST}:3306/${AUTH_DB_NAME}
    username: ${DB_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8082